<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      /*   1.如何改变promise的状态
      resolve()
      reject()
      抛出异常  throw  new error() 
      
      2.一个promise指定多个成功、失败的回调，都会调用吗？

      当promise状态改变时，都会调用
      */

      let p1 = new Promise((resolve, reject) => {
        throw new Error('出错了')
      })

      p1.then(
        (val) => {
          console.log(val)
        }
        // (reason) => {
        //   console.log(reason, '22')
        // }
      ).catch((err) => {
        console.log(err, '333')
      })
      console.log(0)
      p1.then(
        (val) => {
          console.log(val, '44')
        },
        (reason) => {
          console.log(reason, '55')
        }
      )
      console.log(1)
    </script>
  </body>
</html>
